name: Build

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      RUST_VERSION: '1.76.0'
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Cache Cargo dependencies
      uses: actions/cache@v2
      with:
        path: ~/.cargo
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-

    - name: Install
      uses: actions-rs/toolchain@v1
      with:
          toolchain: ${{ env.RUST_VERSION }}
          override: true

    - name: Build
      run: |        
        cargo build

    - name: Archive compiled program
      uses: actions/upload-artifact@v2
      with:
        name: rust-devcontainer
        path: ./target/debug/rust-devcontainer

    - name: Get version from Cargo.toml
      id: get_version
      run: echo "::set-output name=version::$(awk -F'["]' '/^version[ ]*=/ {print $2}' Cargo.toml)"

    - name: Get latest tag
      id: get_latest_tag
      run: |
        latest_tag=$(git tag | sort -g | tail -1)
        echo "::set-output name=latest_tag::${latest_tag}"

    - name: Calculate new tag
      id: calculate_tag
      run: echo "::set-output name=new_tag::$(python3 calculate_tag.py ${{ steps.get_version.outputs.version }} ${{ steps.get_latest_tag.outputs.latest_tag }})"

    - name: Tag output
      run: git tag ${{ steps.calculate_tag.outputs.new_tag }}

    - name: Push tag
      run: git push --tags    

    # Build Docker image
    - name: Build Docker image
      run: docker build -t horowitzathome/rust-devcontainer:latest .  

    # Log in to DockerHub
    - name: Log in to DockerHub
      run: docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD

    # Push Docker image to DockerHub
    - name: Push Docker image to DockerHub
      run: docker push horowitzathome/rust-devcontainer:latest  